language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.8"
  - "5.12"
  - "6.11"
  - "7.10"
  - "8.2"
sudo: false
dist: precise
before_install:
  # Skip updating shrinkwrap / lock
  - "npm config set shrinkwrap false"

  # Remove all non-test dependencies
  - npm rm --save-dev bluebird
  - npm rm --save-dev co
  - npm rm --save-dev cogent
  - npm rm --save-dev csv-parse
  - npm rm --save-dev gnode
  - npm rm --save-dev raw-body
  - npm rm --save-dev stream-to-array

  # Setup Node.js version-specific dependencies
  - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 4 || npm rm --save-dev nyc"
  - "test $(echo $TRAVIS_NODE_VERSION | cut -d. -f1) -ge 4 || npm rm --save-dev $(grep -E '\"eslint\\S*\"' package.json | cut -d'\"' -f2)"
script:
  # Run test script, depending on nyc install
  - "test ! -z $(npm -ps ls nyc) || npm test"
  - "test   -z $(npm -ps ls nyc) || npm run-script test-travis"
  - "test   -z $(npm -ps ls eslint) || npm run-script lint"
after_script:
  - "test -d .nyc_output && npm install coveralls@2 && nyc report --reporter=text-lcov | coveralls"
