language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.9"
  - "5.12"
  - "6.15"
  - "7.10"
  - "8.14"
  - "9.11"
  - "10.13"
  - "11.1"
sudo: false
dist: precise
before_install:
  # Configure npm
  - |
    # Skip updating shrinkwrap / lock
    npm config set shrinkwrap false
  # Remove all non-test dependencies
  - |
    # Remove build dependencies
    npm rm --save-dev bluebird
    npm rm --save-dev co
    npm rm --save-dev cogent
    npm rm --save-dev csv-parse
    npm rm --save-dev gnode
    npm rm --save-dev raw-body
    npm rm --save-dev stream-to-array
  # Setup Node.js version-specific dependencies
  - |
    # mocha for testing
    # - use 1.x for Node.js < 0.8
    # - use 2.x for Node.js < 0.10
    # - use 3.x for Node.js < 6
    if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -eq 0 && "$(cut -d. -f2 <<< "$TRAVIS_NODE_VERSION")" -lt 8 ]]; then
      npm install --save-dev mocha@1.21.5
    elif [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -eq 0 && "$(cut -d. -f2 <<< "$TRAVIS_NODE_VERSION")" -lt 10 ]]; then
      npm install --save-dev mocha@2.5.3
    elif [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 6 ]]; then
      npm install --save-dev mocha@3.5.3
    fi
  - |
    # nyc for coverage
    # - remove on Node.js < 6
    if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 6 ]]; then
      npm rm --save-dev nyc
    fi
  - |
    # eslint for linting
    # - remove on Node.js < 6
    if [[ "$(cut -d. -f1 <<< "$TRAVIS_NODE_VERSION")" -lt 6 ]]; then
      node -pe 'Object.keys(require("./package").devDependencies).join("\n")' | \
        grep -E '^eslint(-|$)' | \
        xargs npm rm --save-dev
    fi
script:
  - |
    # Run test script, depending on nyc install
    if [[ -n "$(npm -ps ls nyc)" ]]; then
      npm run-script test-travis
    else
      npm test
    fi
  - |
    # Run linting, depending on eslint install
    if [[ -n "$(npm -ps ls eslint)" ]]; then
      npm run-script lint
    fi
after_script:
  - |
    # Upload coverage to coveralls if exists
    if [[ -d .nyc_output ]]; then
      npm install --save-dev coveralls@2
      nyc report --reporter=text-lcov | coveralls
    fi
